### ISSUE TITLE
Where does this store state

### ISSUE THREAD

**Issue by rmetcalf9** [m0n0l0c0/gitbook-plugin-todos-list#1]
I am interested in todo's in gitbook.
I have looked at your code. I can't work out how it will keep track of which todo's are done and which are not done, and also where will this information be stored?

**Comment by geblanco** [comment]
Hi @rmetcalf9,

There is no way to mark a todo as completed right now, and it's not clear to me either how this can be done.
I have been thinking about it, my best guess is by passing a "completed" parameter to the filter (eg: `{{ "Buy coffee" | todo(done) }}`) so that it can automatically mark that line as ~~ToDo:= Buy coffee~~ and do it in the todos block also, but I'm not completely sure. Any feedback/ideas are welcome!

All information about todos is to be stored within the `{% todos %} {% endtodos %}` if you have that block anywhere in your docs.

Let me know what you think about this.

Regards,

**Comment by geblanco** [comment]
Hi @rmetcalf9,

Now you can mark a todo as done, just pass `true` to the filter like `{{ "Buy apples" | todo(true) }}` and it will appear as done, also a checked checkbox will appear in the todos block.

I give this as closed, regards!

**Comment by rmetcalf9** [comment]
Hi,
Thanks that is a good solution
Robert
